### ISSUE TITLE
Some engines can't swap2, remove useless engines

### ISSUE THREAD

**Issue by felix-22** [nguyencongminh090/SWAP2GUI#1]
It seems you can remove them, because they don't support swap2 and just take up space unnecessarily:
- slowrenju doesn't even spent a second on thinking nor puts a single move...
- embryo does think but puts just a single move...

```
SWAP2GUI package size:               ZIPPED   UNZIPPED
with Embryo and slowrenju:           10,4 MB  57,1 MB
without Embryo and slowrenju:         8.7 MB  14,8 MB
```

<details not-open>
<summary>slowrenju</summary>

![slowrenju](https://user-images.githubusercontent.com/75935068/132470844-e0301cf9-2d29-416f-889e-027e62b85355.gif)
</details>

<details not-open>
<summary>embryo</summary>

![embryo](https://user-images.githubusercontent.com/75935068/132470832-4d87e2e8-0c41-4fd1-8cd4-87d906c955e1.gif)

</details>

**Comment by nguyencongminh090** [comment]
I got it. I wrote it last year and I put some engines to test. Now I'm rewriting this tool.
